home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('index', views.index, name='index'),

    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('register', views.register, name='register'),

    # path('experiment', views.Experiment.as_view(), name='experiment'),
    # path('ajaxbase', views.ajax, name='ajaxify'),
    # url('all', views.all, name='all'),

    path('todo', views.TodoList.as_view(), name='todo'),
    path('add-todo', views.AddTodo.as_view(), name='add-todo'),
    path('<int:pk>/update-todo', views.TodoUpdate.as_view(), name='update-todo'),
    path('<int:pk>/delete-todo', views.TodoDelete.as_view(), name='delete-todo'),

    path('<int:todo_id>/add-task', views.AddTask.as_view(), name='add-task'),
    path('<int:todo_id>/view-task', views.TaskList.as_view(), name='view-task'),
    path('<int:pk>/update-task', views.TaskUpdate.as_view(), name='update-task'),
    path('<int:pk>/is-done-task', views.is_done_task, name='done-task'),
    path('<int:pk>/delete-task', views.TaskDelete.as_view(), name='delete-task'),
    
    path('<int:pk>/add-comment', views.AddComment.as_view(), name='add-comment'),
    path('<int:pk>/view-comment', views.CommentList.as_view(), name='view-comment'),
    path('<int:pk>/update-comment', views.CommentUpdate.as_view(), name='update-comment'),
    path('<int:pk>/delete-comment', views.CommentDelete.as_view(), name='delete-comment'),
    
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date

# Create your models here.
CHOICES = (('High','High'),('Normal','Normal'))


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)

    def get_absolute_url(self):
        return reverse('home:add-task', args=[self.pk])

    def __str__(self):
        return str(self.title)


class Task(models.Model):
    todo_list = models.ForeignKey(Todo, on_delete= models.CASCADE)
    task_name = models.CharField(max_length=250)
    priority = models.CharField(max_length=25, choices=CHOICES)
    is_done = models.BooleanField(default=False)
    deadline = models.DateField()

    def get_absolute_url(self):
        return reverse('home:add-comment', args=[self.pk])

    def __str__(self):
        return str(self.task_name)


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete= models.CASCADE)
    content = models.CharField(max_length=250)
    file = models.FileField()

    def get_absolute_url(self):
        return reverse('home:index')

    def __str__(self):
        return "just_a_comment"

home/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from .models import Todo, Task, Comment
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from django.http import JsonResponse
from django.views import View
from django.core import serializers




# Create your views here.

def home(request):
    return render(request, 'home/home.html', {})

def index(request):
    return render(request, 'home/index.html', {})
    
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:login')
    else:
        form = UserCreationForm()
        context = {'form': form}
        return render(request, 'home/register.html', context)

def is_done_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = not  task.is_done
    task.save()
    return HttpResponse(status=204)

class Login(LoginView):
    pass


class Logout(LogoutView):
    pass


class TodoList(ListView):
    model = Todo
    template_name = 'home/todo_list.html'
    context_object_name = 'todo_list'
    
    def  get_queryset(self):
        return Todo.objects.filter(user=self.request.user)


class TaskList(ListView):
    template_name = 'home/task_list.html'
    context_object_name = 'todo'

    def get_queryset(self):
        return Todo.objects.filter(pk=self.kwargs['todo_id'])[0]


class CommentList(ListView):
    template_name = 'home/comment_list.html'
    context_object_name = 'task'

    http_method_names = ['get',]

    def get_queryset(self):
        return Task.objects.filter(pk=self.kwargs['pk'])[0]


class AddTodo( CreateView):
    model = Todo
    fields = ['title',]

    def form_valid(self, form):
        user = User.objects.filter(id=self.request.user.pk)[0]
        form.instance.user = user
        return super().form_valid(form)


class AddTask(CreateView):
    model = Task
    fields = [
        'task_name',
        'priority',
        'deadline',
    ]

    def form_valid(self, form):
        todo_list =Todo.objects.filter(pk=self.kwargs["todo_id"])[0]
        form.instance.todo_list = todo_list
        form.instance.is_done = False
        return super().form_valid(form)


class AddComment(CreateView):
    model = Comment
    fields = {
        'content',
        'file',
    }
    

    def form_valid(self, form):
        print(form)
        print(self.kwargs["pk"])
        task = Task.objects.filter(pk=self.kwargs["pk"])[0]
        form.instance.task = task 
        return super().form_valid(form)

    def form_invalid(self, form):
        print(form)
        return HttpResponse("This was invalid")


class TodoUpdate(UpdateView):
    model = Todo
    fields = ['title']


class TaskUpdate(UpdateView):
    model = Task
    fields = [
        'task_name',
        'priority',
        'is_done',
        'deadline'
    ]


class CommentUpdate(UpdateView):
    model = Comment
    fields = [
        'content',
        'file'
    ]


class AjaxDeleteView(SingleObjectMixin, View):
    """
    Works like DeleteView, but without confirmation screens or a success_url.
    """
    def post(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponse(status=204)
    
    def get(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponse(status=204)


class TodoDelete(AjaxDeleteView):
    model = Todo


class TaskDelete(AjaxDeleteView):
    model = Task


class CommentDelete(AjaxDeleteView):
    model = Comment


# def all(request):
#     todos = Todo.objects.filter(user=request.user)
#     return render(request, 'home/all.html', {'todos': todos})

# def ajax(request):
#     return  render(request, 'home/ajaxbase.html', {})

# def todolist(request):
#     context = {}
#     if request.user.is_authenticated:
#         all_todo = Todo.objects.filter(user=request.user)
#         for todo in all_todo:
#             context[todo.title]= Task.objects.filter(todo_list=todo)
#         context['all_todo'] = all_todo
#     return  render(request, 'home/todo_list.html', context)    


# class Experiment(CreateView):
#     model = Todo
#     fields = ['title',]

# class AjaxableResponseMixin:
#     def form_invalid(self, form):
#         response = super().form_invalid(form)
#         if self.request.is_ajax():
#             return HttpResponse(form.errors, status=400)
#         else:
#             return response

#     def form_valid(self, form):
#         response = super().form_valid(form)
#         if self.request.is_ajax():
#             print("We are in here", response)
#             return HttpResponse("Hi")
#         else:
#             print("This is not ajax")
#             return response

home/templates/home/ajaxbase.html
<!DOCTYPE html>
<html lang="en" xmlns:home="http://www.w3.org/1999/xhtml">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Marck+Script&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <meta charset="UTF-8">
    {% block title %} <title>Title</title> {% endblock %}
</head>
<div class="container">

    <div class="item">
      One of three columns
    </div>
    <div class="item">
      One of three columns
    </div>
    <div class="item">
      One of three columns
    </div>

</div>
<div id="demo"></div>

<script>
$(document).ready(function(){
  makeCall()
});
function makeCall(){
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
     document.getElementById("demo").innerHTML = this.responseText;
    }
  };
  xhttp.open("GET", "/todo", true);
  xhttp.send();
}
</script>

home/templates/home/all.html
{% extends 'home/base.html' %}

{% block body%}
    <div class="container-fluid col-md-8 col-sm-8">
                {% for todo in todos%}
            <ul id="todo_{{todo.pk}}">
                <div class="todo_title" value="{{todo.pk}}">{{ todo.title }}&nbsp; <span class='glyphicon glyphicon-pencil' aria-hidden='true' ></span>&nbsp;</a>
                    &nbsp;<form method="POST" style="display: inline;" action="{% url 'home:delete-todo' todo.pk %}">{% csrf_token %}
                    <input type="hidden" name="todo_id" value="{{ todo.pk }}" />
                        <button type="submit" class="btn btn-danger btn-xs">
                        <span class="glyphicon glyphicon-remove"></span>
                                        </button></form></div>

                    <ul  class="task_{{todo.pk}}">
                    {% for task in todo.task_set.all%}
                    <ul    id="task_{{task.pk}}"> <div class="task_name" value="{{task.pk}}" {% if task.is_done %} style = "background-color: greenyellow;" {% endif %}
                         {% if task.priority == "High" %} style = "background-color: orange;" {% else %} style = "background-color: skyblue;" {% endif %} >
                        {{ task.task_name }} &nbsp <a href='{%url 'home:logout' %}'> <span class='glyphicon glyphicon-ok' aria-hidden='true' ></span>&nbsp</a> <span class='glyphicon glyphicon-pencil' aria-hidden='true' ></span>&nbsp;</a>
                    <a href='{%url 'home:logout' %}'>
                    <span class='glyphicon glyphicon-trash' aria-hidden='true' ></span>&nbsp</a></div>
                            <ul  class="comment_{{task.pk}}" >
                            {% for comment in task.comment_set.all%}
                                <ul id="comment_{{comment.pk}}">
                                {{ comment.content }}<br> <a href="{{ comment.file.url}}">File</a> &nbsp <span class='glyphicon glyphicon-pencil' aria-hidden='true' ></span>&nbsp;</a>
                    <a href='{%url 'home:logout' %}'>
                    <span class='glyphicon glyphicon-trash' aria-hidden='true' ></span>&nbsp</a>
                                </ul>
                            {% endfor %}
                            </ul>
                        </ul>
                    {% endfor %}
                    </ul>
            </ul>
        {% endfor %}
    </div>
    <div id="editor">

    </div>

<style>
{% for todo in todos %}
#todo_{{todo.pk}} .task_{{todo.pk}}{
    display:none;
}
#todo_{{todo.pk}}:hover .task_{{todo.pk}}{
    display:inline;
}
{% endfor %}
</style>
{%endblock%}
{% block javascript%}
<script>

$(".todo_title").click(function(){
  var pk = $(this).attr('value');
  console.log("this too", pk, this);
  editTodo(pk);
  function editTodo(pk){
    $.ajax({
        url: "/" + pk + "/add-task",
        type: 'GET',
        dataType: 'html', // added data type
        success: function(res) {
            console.log(res);
            document.getElementById("editor").innerHTML = res;
            document.getElementById("task-form").setAttribute('action', "/" +pk + "/add-task");
            var task_form = $("#task-form");
            task_form.submit(function(e){
            console.log(e);
            e.preventDefault();
            e.stopPropagation();
            var form = $(this);
            var url = form.attr('action');
            $.ajax({
            type: 'POST',
            url: url,
            data: form.serialize(),
            success: function(data){
<!--                document.getElementById("editor").innerHTML = "";-->
                document.getElementById("editor").innerHTML = data;
                var value = $(#comment-btn).attr('value');
                console.log(data, value);
<!--                document.getElementById("comment-form").setAttribute('action', '/'+$(#comment-btn).getattribute();+'/add-comment');-->
<!--                console.log(data);-->
<!--                    var comment_form = $("#comment-form");-->
<!--                    comment_form.submit(function(e){-->
<!--                    console.log(e);-->
<!--                    e.preventDefault();-->
<!--                    e.stopPropagation();-->
<!--                    var form = $(this);-->
<!--                    var url = form.attr('action');-->
<!--                        $.ajax({-->
<!--                        type: 'POST',-->
<!--                        url: url,-->
<!--                        data: form.serialize(),-->
<!--                        success: function(data){-->
<!--                                    console.log(data);-->
                                    }
            });
            });

            }
        });
<!--    })-->
}
      })
<!--            };-->
<!--            });-->
;
;

$(".task_name").click(function(){
  var pk = $(this).attr('value');
  console.log("this too", pk, this);
  editTask(pk);
function editTask(pk){
$.ajax({
        url: "/" +pk + "/add-comment",
        type: 'GET',
        dataType: 'html', // added data type
        success: function(res) {
            console.log(res);
            document.getElementById("editor").innerHTML = res;
            }
        });
    }
});

$(".task_name").click(function(){
  var pk = $(this).attr('value');
  editTask(pk);
function editTask(pk){
        $.ajax({
            url: "/" +pk + "/view-comment",
            type: 'GET',
            dataType: 'html', // added data type
            success: function(res) {
                    console.log(res);
                        document.getElementById("editor").innerHTML = res
                    }
                    });

      }
});


var task_form = $("#task-form");
task_form.submit(function(e){
console.log(e);
e.preventDefault();
e.stopPropagation();
var form = $(this);
var url = form.attr('action');

$.ajax({
type: 'POST',
url: url,
data: form.serialize(),
success: function(data){
    alert(data);
}
});
});



<!--task_form.submit(function(event){-->
<!-- var todo = task_form.data["id"]-->
<!-- var task_name = task_form.find-->
<!--});-->

</script>

{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en" xmlns:home="http://www.w3.org/1999/xhtml">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Marck+Script&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <meta charset="UTF-8">
    {% block title %} <title>Home</title> {% endblock %}
</head>

<nav class="navbar">
    <div class="container-fluid">
        <!-- Header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        
            <a class="navbar-brand" href='{%url 'home:index' %}' style='color: midnightblue;'><u> To-Do</u> </a>

        </div>

        <!-- Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right" >
                {% if not request.user.is_authenticated %}
                    <li><a href='{%url 'home:register' %}' style='color: midnightblue;' >
                        <span class='glyphicon glyphicon-off' aria-hidden='true' ></span>&nbsp; Register</a>
                    </li>
                {% endif %}
                {% if not request.user.is_authenticated %}
                    <li><a href='{%url 'home:login' %}' style='color: midnightblue;' >
                        <span class='glyphicon glyphicon-off' aria-hidden='true' ></span>&nbsp; Login</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li><a href='{%url 'home:logout' %}' style='color: midnightblue;' >
                        <span class='glyphicon glyphicon-off' aria-hidden='true' ></span>&nbsp; Logout</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>

{% block body%}
{% endblock %}

{% block javascript%}   
{% endblock %}

</html>

home/templates/home/comment_list.html
<div class="panel panel-default">
    <div class="panel-body">
        <table class="table">
                                
                                <tr>
                                    Comment &nbsp;&nbsp;&nbsp;&nbsp;<a id='add-comment' href='{% url 'home:add-comment' task.pk %}'><small>
                                    <span class='glyphicon glyphicon-plus' aria-hidden='true' ></span>Add Comment</small></a>              
                                </tr>
                                <hr style="border-width: 3px;">
                                

                   
                            {% for comment in task.comment_set.all %}
                                <tr>

                                    <div class="comment" value="{{comment.pk}}"> {{ comment.content }} </div>
                                    
                                    <div class='attachment' style='display: inline;' >
                                    <a href={{comment.file.url}} target="_blank" >
                                        <button type="button" class="btn btn-info btn-xs" >
                                            <span class='glyphicon glyphicon-download' aria-hidden='true' ></span>
                                            Attachment
                                             
                                        </button>
                                    </a>
                                    </div>
                                    
                                    <div class='comment_update' style='display: inline;' value='{% url 'home:update-comment' comment.pk %}'>
                                        <button type="submit"  class="btn btn-success btn-xs">
                                            <span class='glyphicon glyphicon-pencil' aria-hidden='true' ></span>
                                        </button>
                                    </div>

                                    <div class='comment_delete' style='display: inline;' value='{% url 'home:delete-comment' comment.pk %}'>
                                        <button class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>
                                        </button>
                                    </div>
                                                                            
                                </tr>
                                <hr>  
                            {% endfor %}
                            
                                            
            </table>

    </div>
</div>

home/templates/home/confirm_delete.html
<form method="post" enctype="multipart/form-data" id="comment-form" action="{{ form.pk }}" >
{% csrf_token %}
<h4>Are you sure about this?</h4>
{{form.as_p}}
<button type="submit" value="{{ form.instance.task.pk}}" id="comment-btn">Submit</button>
</form>
{{form.errors}}

home/templates/home/home.html
{% extends 'home/base.html' %}

{% block body %}

<div id='about'>
<h2>Welcome</h2>
<p>This is a To-do app, its features are as follows:</p>
<ul>
<li> The user can add Todo lists, corresponding Tasks and Comments with File Attachments. </li>
<li> The user can if registered and logged in Delete, View or Update any of their user data. </li>
<li> All communication after Login happens through Ajax calls. </li>
<li> Tasks with a a background colour of lightsalmon are high priority and lightcyan indicates normal priority tasks. </li>
<li> Tasks with a strike-through indicated that they have been completed. </li>
</ul>

</div>

{% endblock %}

home/templates/home/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css" />
</head>
<body>
    <div class="container">
        <div class="item">
            <ul>
                <li>hi</li>
                <li>bi</li>
            </ul>
        </div>
        <div class="item">
            <ul>
                <li>hi</li>
                <li>bi</li>
            </ul>
        </div>
        <div class="item">
            <ul>
                <li>hi</li>
                <li>bi</li>
            </ul>
        </div>
    </div>


</body>
</html>

home/templates/home/list_comment.html
<table>
<tbody>
{%for comment in all_comments%}
<tr class="comment" value="{{comment.pk}}">
    {{comment.content}} <a href="{{comment.file.url}}"> File</a>
</tr>

{% endfor %}
</tbody>

</table>

home/templates/home/list_task.html
<tbody>
{%for task in all_tasks%}
<tr class="task" value="{{task.pk}}">
{{task.task_name}} + {{task.pk}}
</tr>

{% endfor %}
</tbody>
<div id="targetComment"></div>

<script>
$(".task").click(function(){
  var pk = $(this).attr('value')
  callComment(pk)
});
function callComment(pk){
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
     document.getElementById("targetComment").innerHTML = this.responseText;
    }
  };
  xhttp.open("GET", "/" + pk + "/view-comment", true);
  xhttp.send();
}
</script>

home/templates/home/register.html
{% extends 'home/base.html'%}

{% block body%}
<div class="container">
    <h2>Register</h2>
    <form method="post" action="">
        {% csrf_token%}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>
</div>

{% endblock %}

home/templates/home/task_form.html
<form method="post" id="task-form" action="" >
{% csrf_token %}
{{ form.as_p }}
<small>Date format: yyyy-mm-dd</small><br>
<button type="submit" id="task-submit" class="btn btn-success" >Create</button>
</form>

home/templates/home/task_list.html
<div class="panel panel-default">
    <div class="panel-body">
        <table class="table">

            <tr>
                Task &nbsp;&nbsp;&nbsp;&nbsp;<a id ='add-task' href='{% url 'home:add-task' todo.pk %}'><small>
                <span class='glyphicon glyphicon-plus' aria-hidden='true' ></span>Add Task</small></a>              
            </tr>

            <hr style="border-width: 3px;">

            {% for task in todo.task_set.all%}
                <tr >
                                
                    <div class="tasks" value="{{task.pk}}"
                        {% if task.priority == "High" %} style = "background-color: lightsalmon;" {% else %} style = "background-color: lightcyan;" {% endif %}>
                             {% if task.is_done %} 
                             <strike>
                             {% endif %}
                              {{ task.task_name }}
                             {% if task.is_done %} 
                             </strike>
                             {% endif %} 
                             
                    </div>

                    <div class='task_done' style='display: inline;' value='{% url 'home:done-task' task.pk %}'>
                        <button type="submit"  class="btn btn-info btn-xs">
                            <span class='glyphicon glyphicon-ok' aria-hidden='true' ></span>
                        </button>
                    </div>

                    <div class='task_update' style='display: inline;' value='{% url 'home:update-task' task.pk %}'>
                        <button type="submit"  class="btn btn-success btn-xs">
                            <span class='glyphicon glyphicon-pencil' aria-hidden='true' ></span>
                        </button>
                    </div>

                    <div class='task_delete' style='display: inline;' value='{% url 'home:delete-task' task.pk %}'>
                        <button type="submit"  class="btn btn-danger btn-xs">
                            <span class="glyphicon glyphicon-remove" aria-hidden='true' ></span>
                        </button>
                    </div>
                    
                    
                </tr>

                <hr>  
            {% endfor %}

        </table>
    </div>
</div>

home/templates/home/todo_form.html
<form method="post" id="todo-form" data-id="{{post.pk}}" action='{% url 'home:add-todo' %}'>
{% csrf_token %}
{{form.as_p}}
<button type="submit" id='todo-submit' class="btn btn-success" >Create</button>
</form>

home/templates/home/todo_list.html
<div class="panel panel-default">
        <div class="panel-body">
            <table class="table">
                    
                    <tr>
                        Todo &nbsp;&nbsp;&nbsp;&nbsp;
                        <a id="add-todo" href='{% url 'home:add-todo' %}'><small><span class='glyphicon glyphicon-plus' aria-hidden='true' ></span>New Todo</small></a>
                    </tr>
                    <hr style="border-width: 3px;">
                    
                        
                {% for todo in todo_list %}
                        <tr>
                                <div class="todos" value="{{todo.pk}}"> 
                                    {{ todo.title }} 
                                </div>
                                
                                <div class='todo_update' style='display: inline;' value='{% url 'home:update-todo' todo.pk %}'>
                                    <button type="submit"  class="btn btn-success btn-xs">                       
                                        <span class='glyphicon glyphicon-pencil' aria-hidden='true' ></span>
                                    </button>
                                </div>

                                <div class='todo_delete' style='display: inline;' value='{% url 'home:delete-todo' todo.pk %}'>
                                    <button type="submit"  class="btn btn-danger btn-xs">                       
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </button>
                                    
                                </div>
                                
                        </tr>
                    <hr>
                {% endfor %}
        </table>
    </div>
</div>